In [13]:
import pandas as pd
import glob

In [14]:
path = 'Bayesian_Logistic_Regression/Stocks'

all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename)
    li.append(df)

frame = pd.concat(li, axis=0)

In [15]:
frame

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,1990-02-16,0.00,0.06,0.06,0.06,940636800.0,0.0,0.0
1,1990-02-20,0.00,0.06,0.06,0.06,151862400.0,0.0,0.0
2,1990-02-21,0.00,0.06,0.06,0.06,70531200.0,0.0,0.0
3,1990-02-22,0.00,0.06,0.06,0.06,45216000.0,0.0,0.0
4,1990-02-23,0.00,0.06,0.06,0.06,44697600.0,0.0,0.0
...,...,...,...,...,...,...,...,...
4059,2020-08-06,202.97,209.95,202.40,207.79,5113300.0,0.0,0.0
4060,2020-08-07,206.62,206.94,198.58,201.05,5422300.0,0.0,0.0
4061,2020-08-10,200.40,201.48,195.72,197.16,5528200.0,0.0,0.0
4062,2020-08-11,193.62,195.84,191.72,191.99,5015400.0,0.0,0.0
4063,2020-08-12,193.00,195.42,192.12,192.62,3980300.0,0.0,0.0